version: '3'

services:

  virtual-desktop:
      image: dorowu/ubuntu-desktop-lxde-vnc:bionic-lxqt
      volumes:
        - ./robot:/home/robot
      ports:
        - '5910:5900'
      environment:
        - USER=robot
        - PASSWORD=robot
        - MINIO_ACCESS_KEY=V42FCGRVMK24JJ8DHUYG
        - MINIO_SECRET_KEY=bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - './minio/data/:/data'
    environment:
      - MINIO_ACCESS_KEY=V42FCGRVMK24JJ8DHUYG
      - MINIO_SECRET_KEY=bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
    command: server /data